FROM python:3.12

WORKDIR /app
COPY ./requirements.txt /app/
RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

WORKDIR /app/code
CMD uvicorn controller:app --host 0.0.0.0 --port 8000 --reload --log-level debug